In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('54fba223-5ddc-4139-9503-43cf7c5f8eea_Data.csv')

In [3]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],...,2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025],2026 [YR2026]
0,Afghanistan,AFG,Agricultural land (% of land area),AG.LND.AGRI.ZS,58.32298422,58.30765221,58.30765221,58.16046487,57.97494749,57.8829554,...,58.12366803,58.27698818,58.27698818,58.80747589,..,..,..,..,..,..
1,Afghanistan,AFG,Annual CO2 combustion emissions at operating c...,CC.COAL.EMIS.CO,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,Afghanistan,AFG,Annual CO2 combustion emissions at proposed co...,CC.COAL.EMPR.CO,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,Afghanistan,AFG,Annual coal production (Mt per year) - Operating,CC.COAL.PROD.OP,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,Afghanistan,AFG,Annual coal production (Mt per year) - Propose...,CC.COAL.PROD.PR,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [4]:
df['Series Code'].unique()

array(['AG.LND.AGRI.ZS', 'CC.COAL.EMIS.CO', 'CC.COAL.EMPR.CO',
       'CC.COAL.PROD.OP', 'CC.COAL.PROD.PR', 'CC.COAL.EMIS.CH',
       'CC.COAL.EMPR.CH', 'AG.LND.ARBL.ZS', 'CC.PRO.ANI',
       'CC.CO2.EMSE.BL', 'CC.CO2.EMSE.BF', 'CC.CO2.EMSE.EH',
       'CC.CO2.EMSE.EN', 'CC.CO2.EMSE.FE', 'CC.CO2.EMSE.IP',
       'CC.CO2.EMSE.LU', 'CC.CO2.EMSE.MC', 'CC.CO2.EMSE.OF',
       'CC.CO2.EMSE.EL', 'CC.CO2.EMSE.IL', 'CC.CO2.EMSE.TR',
       'CC.ELEC.CON', 'CC.ELEC.GEN', 'CC.ECH.AFO', 'CC.ECH.BCR',
       'CC.ECH.EAL', 'CC.ECH.EFE', 'CC.ECH.FGE', 'CC.ECH.FTR',
       'CC.ECH.FOS', 'CC.ECH.FFR', 'CC.ECH.IPA', 'CC.ECH.LUC',
       'CC.ECH.LUL', 'CC.ECH.MMA', 'CC.ECH.OEU', 'CC.ECH.RCA',
       'CC.ECH.SVF', 'CC.ECO.AFO', 'CC.ECO.DOC', 'CC.ECO.EAL',
       'CC.ECO.FGE', 'CC.ECO.FOS', 'CC.ECO.FOR', 'CC.ECO.LUC',
       'CC.ECO.LUL', 'CC.ECO.NFC', 'CC.ECO.OEU', 'CC.EAR.AFO',
       'CC.EAR.AGS', 'CC.EAR.BCR', 'CC.EAR.DOS', 'CC.EAR.CRE',
       'CC.EAR.DOC', 'CC.EAR.DON', 'CC.EAR.EAL', 'CC.EAR.EFE',
       'CC.EAR.FGE', 'CC.EAR.FTR', 'CC.EAR.FOS', 'CC.EAR.FFR',
       'CC.EAR.FOR', 'CC.EAR.IPA', 'CC.EAR.LUC', 'CC.EAR.LUL',
       'CC.EAR.SAS', 'CC.EAR.MLP', 'CC.EAR.MMA', 'CC.EAR.NFC',
       'CC.EAR.OEU', 'CC.EAR.SVF', 'CC.EAR.RCA', 'CC.EAR.SFE',
       'CC.ECA.AFO', 'CC.ECA.BCR', 'CC.ECA.EAL', 'CC.ECA.EFE',
       'CC.ECA.FGE', 'CC.ECA.FTR', 'CC.ECA.FOS', 'CC.ECA.FFR',
       'CC.ECA.IPA', 'CC.ECA.LUC', 'CC.ENA.EAL', 'CC.ENA.FGE',
       'CC.ENA.FTR', 'CC.ENA.FFR', 'CC.ENA.IPA', 'CC.ENA.LUC',
       'CC.ECA.LUL', 'CC.ECA.MMA', 'CC.ECA.OEU', 'CC.ECA.RCA',
       'CC.ECA.SVF', 'CC.ENA.AFO', 'CC.ENA.AGS', 'CC.ENA.BCR',
       'CC.ENA.CRE', 'CC.ENA.DON', 'CC.ENA.LUL', 'CC.ENA.SAS',
       'CC.ENA.MLP', 'CC.ENA.MMA', 'CC.ENA.OEU', 'CC.ENA.SVF',
       'CC.ENA.SFE', 'CC.ESG.AGFE', 'CC.ESG.AGMA', 'CC.ESG.CMFE',
       'CC.ESG.CMMA', 'CC.ESG.CNFE', 'CC.ESG.CNMA', 'CC.ESG.EUFE',
       'CC.ESG.EUMA', 'CC.ESG.FBFE', 'CC.ESG.FBMA', 'CC.ESG.INFE',
       'CC.ESG.INMA', 'CC.ESG.MAFE', 'CC.ESG.MAMA', 'CC.ESG.MIFE',
       'CC.ESG.MIMA', 'CC.ESG.OSFE', 'CC.ESG.OSMA', 'CC.ESG.PAFE',
       'CC.ESG.PAMA', 'CC.ESG.PSFE', 'CC.ESG.PSMA', 'CC.ESG.SEFE',
       'CC.ESG.SEMA', 'CC.ESG.TCFE', 'CC.ESG.TCMA', 'CC.FGHG.SYS.CS',
       'CC.FGHG.SYS.EO', 'CC.FGHG.SYS.LU', 'CC.FGHG.SYS.PC',
       'CC.FGHG.SYS.PR', 'CC.FGHG.SYS.PD', 'CC.FGHG.SYS.RE',
       'CC.FGHG.SYS.TR', 'NY.GDP.MKTP.CD', 'NY.GDP.MKTP.KD.ZG',
       'NY.GDP.PCAP.CD', 'CC.GHG.FSYS.CO', 'CC.GHG.FSYS.FG',
       'CC.GHG.FSYS.CH', 'CC.GHG.FSYS.NO', 'CC.GHG.GRPE',
       'CC.EN.ATM.COAL.CE', 'CC.NCO.GHG.AG', 'CC.NCO.GHG.EN',
       'CC.NCO.GHG.FE', 'CC.NCO.GHG.IP', 'CC.NCO.GHG.LU', 'CC.NCO.GHG.OF',
       'CC.NCO.GHG.EL', 'CC.NCO.GHG.IL', 'CC.NCO.GHG.WA',
       'CC.OPCO.AG.CA1', 'CC.OPCO.AG.CA2', 'CC.OPCO.AG.CA3',
       'CC.OPCO.AG.CA4', 'CC.OPCO.AG.CA5', 'CC.OPCO.AG.CA6',
       'CC.OPCO.PLTY.CF', 'CC.OPCO.PLTY.IG', 'CC.OPCO.PLTY.SU',
       'CC.OPCO.PLTY.CC', 'CC.OPCO.PLTY.SC', 'CC.OPCO.PLTY.US',
       'CC.OPCO.PLTY.UK', 'CC.PSVOL.MOD.AI', 'CC.PSVOL.MOD.RA',
       'CC.PSVOL.MOD.RO', 'CC.EG.CONS.COAL.PC', 'CC.EG.CONS.GAS.PC',
       'CC.EG.CONS.OIL.PC', 'CC.GHG.PECA', 'SP.POP.TOTL',
       'CC.FOOD.ANIM.ZS', 'AG.LND.FRST.ZS', 'CC.TOTL.COCA.AN',
       'CC.TOTL.COCA.CA', 'CC.TOTL.COCA.CO', 'CC.TOTL.COCA.MB',
       'CC.TOTL.COCA.OP', 'CC.TOTL.COCA.PE', 'CC.TOTL.COCA.PP',
       'CC.TOTL.COCA.RE', 'CC.TOTL.COCA.SH', 'CC.ENTX.ENE.ZS',
       'CC.GHG.EMSE.AG', 'CC.GHG.EMSE.BL', 'CC.GHG.EMSE.BF',
       'CC.GHG.EMSE.EH', 'CC.GHG.EMSE.EN', 'CC.GHG.EMSE.FE',
       'CC.GHG.EMSE.IP', 'CC.GHG.EMSE.LU', 'CC.GHG.EMSE.MC',
       'CC.GHG.EMSE.OF', 'CC.GHG.EMSE.EL', 'CC.GHG.EMSE.IL',
       'CC.GHG.EMSE.TR', 'CC.GHG.EMSE.WA', 'CC.TOT.GHG.GR',
       'SP.URB.TOTL.IN.ZS', nan], dtype=object)

In [5]:
df_filtered = df.loc[df['Series Code'].isin(['AG.LND.AGRI.ZS','AG.LND.ARBL.ZS','CC.CO2.EMSE.BL','CC.CO2.EMSE.BF','CC.CO2.EMSE.EH','CC.CO2.EMSE.EN','CC.CO2.EMSE.FE','CC.CO2.EMSE.IP','CC.CO2.EMSE.LU','CC.CO2.EMSE.MC','CC.CO2.EMSE.OF','CC.CO2.EMSE.EL','CC.CO2.EMSE.IL','CC.CO2.EMSE.TR','CC.ELEC.CON','NY.GDP.MKTP.CD','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.CD','CC.GHG.GRPE','CC.EG.CONS.COAL.PC','CC.EG.CONS.GAS.PC','CC.EG.CONS.OIL.PC','CC.GHG.PECA','SP.POP.TOTL','AG.LND.FRST.ZS','SP.URB.TOTL.IN.ZS'])]

In [6]:
df_filtered['Series Code'].unique()

array(['AG.LND.AGRI.ZS', 'AG.LND.ARBL.ZS', 'CC.CO2.EMSE.BL',
       'CC.CO2.EMSE.BF', 'CC.CO2.EMSE.EH', 'CC.CO2.EMSE.EN',
       'CC.CO2.EMSE.FE', 'CC.CO2.EMSE.IP', 'CC.CO2.EMSE.LU',
       'CC.CO2.EMSE.MC', 'CC.CO2.EMSE.OF', 'CC.CO2.EMSE.EL',
       'CC.CO2.EMSE.IL', 'CC.CO2.EMSE.TR', 'CC.ELEC.CON',
       'NY.GDP.MKTP.CD', 'NY.GDP.MKTP.KD.ZG', 'NY.GDP.PCAP.CD',
       'CC.GHG.GRPE', 'CC.EG.CONS.COAL.PC', 'CC.EG.CONS.GAS.PC',
       'CC.EG.CONS.OIL.PC', 'CC.GHG.PECA', 'SP.POP.TOTL',
       'AG.LND.FRST.ZS', 'SP.URB.TOTL.IN.ZS'], dtype=object)

In [27]:
from pathlib import Path  
filepath = Path('filtered_data.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df_filtered.to_csv(filepath)

In [11]:
# Renaming the year columns.

df_filtered = df_filtered.rename(columns={'1990 [YR1990]':'1990','1991 [YR1991]':'1991','1992 [YR1992]':'1992','1993 [YR1993]':'1993','1994 [YR1994]':'1994','1995 [YR1995]':'1995','1996 [YR1996]':'1996','1997 [YR1997]':'1997','1998 [YR1998]':'1998','1999 [YR1999]':'1999','2000 [YR2000]':'2000','2001 [YR2001]':'2001','2002 [YR2002]':'2002','2003 [YR2003]':'2003','2004 [YR2004]':'2004','2005 [YR2005]':'2005','2006 [YR2006]':'2006','2007 [YR2007]':'2007','2008 [YR2008]':'2008','2009 [YR2009]':'2009','2010 [YR2010]':'2010','2011 [YR2011]':'2011','2012 [YR2012]':'2012','2013 [YR2013]':'2013','2014 [YR2014]':'2014','2015 [YR2015]':'2015','2016 [YR2016]':'2016','2017 [YR2017]':'2017','2018 [YR2018]':'2018','2019 [YR2019]':'2019','2020 [YR2020]':'2020','2021 [YR2021]':'2021','2022 [YR2022]':'2022','2023 [YR2023]':'2023','2024 [YR2024]':'2024','2025 [YR2025]':'2025','2026 [YR2026]':'2026'})

In [16]:
# Getting the year columns as an array so I can easily copy and paste it.

Year_column_list = df_filtered.columns.values
Year_column_list[4:]

array(['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024', '2025', '2026'], dtype=object)

In [29]:
# Using pd.melt() to flatten the table. id_vars is the list of columns not to transpose. value_vars is the list of columsn that will be transpose. 

df_melt = pd.melt(df_filtered, id_vars=['Country Name','Country Code','Series Name','Series Code'], value_vars=['1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000', '2001','2002','2003','2004','2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024', '2025', '2026'], var_name='Year', value_name='Value')
df_melt

,Country Name,Country Code,Series Name,Series Code,Year,Value
0,Afghanistan,AFG,Agricultural land (% of land area),AG.LND.AGRI.ZS,1990,58.32298422
1,Afghanistan,AFG,Arable land (% of land area),AG.LND.ARBL.ZS,1990,12.12762369
2,Afghanistan,AFG,CO2 emissions by sector (Mt CO2 eq) - Building,CC.CO2.EMSE.BL,1990,0.08
3,Afghanistan,AFG,CO2 emissions by sector (Mt CO2 eq) - Bunker F...,CC.CO2.EMSE.BF,1990,0.02
4,Afghanistan,AFG,CO2 emissions by sector (Mt CO2 eq) - Electric...,CC.CO2.EMSE.EH,1990,0.27
...,...,...,...,...,...,...
211635,Zimbabwe,ZWE,Per capita daily oil consumption (barrels per ...,CC.EG.CONS.OIL.PC,2026,..
211636,Zimbabwe,ZWE,Per capita GHG emissions (tons/capita),CC.GHG.PECA,2026,..
211637,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,2026,16390000
211638,Zimbabwe,ZWE,Share of surface occupied by forest (% of total),AG.LND.FRST.ZS,2026,..
211639,Zimbabwe,ZWE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,2026,33.067

In [32]:
from pathlib import Path
filepath_melt = Path('melted_data.csv')  
filepath_melt.parent.mkdir(parents=True, exist_ok=True)  
df_melt.to_csv(filepath_melt)